# Generated by Django 5.2.8 on 2025-11-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='updated_time',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='usersubmission',
            old_name='submitted_time',
            new_name='submitted_at',
        ),
    ]
