# Generated by Django 5.2.8 on 2025-11-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_rename_created_time_questions_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='submitted_at',
        ),
    ]
