# Generated by Django 5.2.8 on 2025-11-08 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_usersubmission_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 8, 10, 56, 50, 516481, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
