# Generated by Django 5.2.8 on 2025-11-08 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_usersubmission_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
