# Generated by Django 5.2.8 on 2025-11-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_alter_questions_created_at_alter_quiz_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='updated_at',
        ),
    ]
